run:
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - gosec

  presets:
    - bugs

  fast: true

issues:
  exclude:
    - ./web
    - ./secrets

output:
  show-stats: true
