version: "3.8"

services:
  # service for authenticate users
  auth-service:
    build:
      context: ./services/auth

    container_name: proxy-auth-service
    restart: unless-stopped

    networks:
      proxy-manager-network:

    ports:
      - "3224:${AUTH_SERVICE_PORT}"

    environment:
      AUTH_TOKEN_TTL: ${JWT_AUTH_TOKEN_TTL}
      AUTH_TOKEN_SECRET: ${JWT_AUTH_TOKEN_SECRET}
      GRPC_SERVER_PORT: ${AUTH_SERVICE_PORT}
      GRPC_SERVER_TIMEOUT: ${AUTH_SERVICE_TIMEOUT}
      DATABASE_URI: ${POSTGRES_URI}

    depends_on:
      migrator:
        condition: service_completed_successfully

  # service for save request
  request-service:
    build:
      context: ./services/proxy-request

    container_name: proxy-request-service
    restart: unless-stopped

    networks:
      proxy-manager-network:

    ports:
      - "3223:${REQUEST_SERVICE_PORT}"

    environment:
      GRPC_SERVER_PORT: ${REQUEST_SERVICE_PORT}
      GRPC_SERVER_TIMEOUT: ${REQUEST_SERVICE_TIMEOUT}
      DATABASE_URI: ${POSTGRES_URI}

    depends_on:
      migrator:
        condition: service_completed_successfully

  # service for migrating
  migrator:
    tty: true
    stdin_open: true

    build:
      dockerfile: ./deploy/docker/migrator.Dockerfile
    container_name: go-migrator

    networks:
      proxy-manager-network:

    volumes:
      - ./migrations:/migrations

    command: migrate -path /migrations -database ${POSTGRES_URI} up

    depends_on:
      db:
        condition: service_healthy
        restart: true

  # postgres db
  db:
    image: postgres:alpine
    container_name: proxy-mananger-db
    restart: unless-stopped

    networks:
      proxy-manager-network:

    ports:
      - "5432:${POSTGRES_PORT}"

    environment:
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  proxy-manager-network:
    name: proxy-manager-network-common
