version: "3.8"

services:
  frontend:
    build:
      context: ./web

    container_name: proxy-manager-frontend
    restart: unless-stopped

    networks:
      proxy-manager-network:

    ports:
      - "${FRONTEND_SERVICE_PORT}:5173"

    environment:
      VITE_BACKEND_URL: ${GATEWAY_SERVICE_BACKEND_URL}

    depends_on:
      gateway-service:
        condition: service_started

  # service gateway for grpc to http
  gateway-service:
    build:
      context: ./services/gateway

    container_name: proxy-gateway-service
    restart: unless-stopped

    networks:
      proxy-manager-network:

    ports:
      - "3030:${GATEWAY_SERVICE_PORT}"

    environment:
      ENV: ${ENV}
      HTTP_SERVER_PORT: ${GATEWAY_SERVICE_PORT}
      HTTP_SERVER_TIMEOUT: ${GATEWAY_SERVICE_TIMEOUT}
      HTTP_SERVER_IDLE_TIMEOUT: ${GATEWAY_SERVICE_IDLE_TIMEOUT}
      HTTP_SERVER_SHUTDOWN_TIMEOUT: ${GATEWAY_SERVICE_SHUTDOWN_TIMEOUT}

      REQUEST_SERVICE_ADDR: "request-service:${REQUEST_SERVICE_PORT}"
      AUTH_SERVICE_ADDR: "auth-service:${AUTH_SERVICE_PORT}"
      MANAGER_SERVICE_ADDR: "manager-service:${MANAGER_SERVICE_PORT}"

    depends_on:
      manager-service:
        condition: service_started
      auth-service:
        condition: service_started
      request-service:
        condition: service_started

  # service for proxy managing
  manager-service:
    build:
      context: ./services/proxy-manager

    container_name: proxy-manager-service
    restart: unless-stopped

    networks:
      proxy-manager-network:

    # ports:
    #   - "3225:${MANAGER_SERVICE_PORT}"

    volumes:
      - ./services/proxy-manager/configs:/configs
      - /var/run/docker.sock:/var/run/docker.sock:rw

    environment:
      ENV: ${ENV}
      CONFIG_PATH: ${MANAGER_SERVICE_CONFIG_PATH}
      GRPC_SERVER_PORT: ${MANAGER_SERVICE_PORT}
      GRPC_SERVER_TIMEOUT: ${MANAGER_SERVICE_TIMEOUT}

    depends_on:
      auth-service:
        condition: service_started
      request-service:
        condition: service_started

  # service for authenticate users
  auth-service:
    build:
      context: ./services/auth

    container_name: proxy-auth-service
    restart: unless-stopped

    networks:
      proxy-manager-network:

    ports:
      - "3224:${AUTH_SERVICE_PORT}"

    environment:
      ENV: ${ENV}
      AUTH_TOKEN_TTL: ${JWT_AUTH_TOKEN_TTL}
      AUTH_TOKEN_SECRET: ${JWT_AUTH_TOKEN_SECRET}
      GRPC_SERVER_PORT: ${AUTH_SERVICE_PORT}
      GRPC_SERVER_TIMEOUT: ${AUTH_SERVICE_TIMEOUT}
      DATABASE_URI: ${POSTGRES_URI}

    depends_on:
      migrator:
        condition: service_completed_successfully

  # service for save request
  request-service:
    build:
      context: ./services/proxy-request

    container_name: proxy-request-service
    restart: unless-stopped

    networks:
      proxy-manager-network:

    ports:
      - "3223:${REQUEST_SERVICE_PORT}"

    environment:
      ENV: ${ENV}
      GRPC_SERVER_PORT: ${REQUEST_SERVICE_PORT}
      GRPC_SERVER_TIMEOUT: ${REQUEST_SERVICE_TIMEOUT}
      DATABASE_URI: ${POSTGRES_URI}

    depends_on:
      migrator:
        condition: service_completed_successfully

  # service for migrating
  migrator:
    build:
      dockerfile: ./deploy/docker/migrator.Dockerfile
    container_name: go-migrator

    networks:
      proxy-manager-network:

    volumes:
      - ./migrations:/migrations

    command: migrate -path /migrations -database ${POSTGRES_URI} up

    depends_on:
      db:
        condition: service_healthy
        restart: true

  # postgres db
  db:
    image: postgres:alpine
    container_name: proxy-manager-db
    restart: unless-stopped

    networks:
      proxy-manager-network:

    # ports:
    #   - "5432:${POSTGRES_PORT}"

    volumes:
      - pgdata:/var/lib/postgresql/data

    environment:
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  proxy-manager-network:
    name: proxy-manager-network-common

volumes:
  pgdata:
    name: proxy-manager-db-volume
    external: true
