services:
  proxy:
    image: go-proxy
    build:
      context: .
      dockerfile: ./docker/proxy.Dockerfile
      target: development

    container_name: go-proxy
    restart: unless-stopped

    # TODO: move volume out of here
    volumes:
      - ./config:/config
    ports:
      - 8123:8123
    environment:
      - ENV=dev
