services:
  # TODO: remove test proxy
  # WARN: could break github actions
  self-controlled-proxy:
    image: go-proxy
    build:
      context: .
      dockerfile: ./docker/proxy.Dockerfile
      target: development

    container_name: self-controlled-proxy
    restart: unless-stopped

    ports:
      - 127.0.0.1:8124:8123
    environment:
      - ENV=dev
      - ADDRESS=0.0.0.0:8123
      - READ_HEADER_TIMEOUT=1s
      - IDLE_TIMEOUT=60s
      - SHUTDOWN_TIMEOUT=10s

  # proxy-manager for starting other proxy and
  proxy-manager:
    image: go-proxy-manager
    build:
      context: .
      dockerfile: ./docker/proxy_manager.Dockerfile
      target: development

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"

    container_name: proxy-manager
    restart: unless-stopped
