services:
  self-controlled-proxy:
    image: go-proxy
    build:
      context: ./services/proxy/

    container_name: self-controlled-proxy
    restart: unless-stopped

    ports:
      - 127.0.0.1:9123:8123
    environment:
      - ENV=dev
      - HOST=0.0.0.0
      - PORT=8123
      - READ_HEADER_TIMEOUT=1s
      - READ_TIMEOUT=60s
      - WRITE_TIMEOUT=60s

  # proxy-manager for starting other proxy and
  proxy-manager:
    image: proxy-manager-service
    build:
      context: ./services/proxy-manager/

    container_name: proxy-manager-service
    restart: unless-stopped

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "./services/proxy-manager/configs/dev.yml:/configs/dev.yml"

    environment:
      - CONFIG_PATH=/configs/dev.yml
