proxy_manager:
  proxies:
    - env: dev
      address: 127.0.0.1:8123
      read_header_timeout: 1s
      read_timeout: 60s
      write_timeout: 60s
      shutdown_timeout: 10s
    - env: dev
      address: 127.0.0.1:8124
      read_header_timeout: 1s
      read_timeout: 60s
      write_timeout: 60s
      shutdown_timeout: 10s
    - env: dev
      address: 127.0.0.1:8125
      read_header_timeout: 1s
      read_timeout: 60s
      write_timeout: 60s
      shutdown_timeout: 10s

  engine:
    check_timeout: 5s
  rpc_server:

docker-client:
  api-version: "1.44"
  host: "unix:///var/run/docker.sock"
  timeout: 5s

proxy_image:
  image: "go-proxy"
