// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: request.proto

package request

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProxyRequestServiceClient is the client API for ProxyRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyRequestServiceClient interface {
	SaveProxyRequest(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error)
}

type proxyRequestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyRequestServiceClient(cc grpc.ClientConnInterface) ProxyRequestServiceClient {
	return &proxyRequestServiceClient{cc}
}

func (c *proxyRequestServiceClient) SaveProxyRequest(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, "/request.ProxyRequestService/SaveProxyRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyRequestServiceServer is the server API for ProxyRequestService service.
// All implementations must embed UnimplementedProxyRequestServiceServer
// for forward compatibility
type ProxyRequestServiceServer interface {
	SaveProxyRequest(context.Context, *SaveRequest) (*SaveResponse, error)
	mustEmbedUnimplementedProxyRequestServiceServer()
}

// UnimplementedProxyRequestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProxyRequestServiceServer struct {
}

func (UnimplementedProxyRequestServiceServer) SaveProxyRequest(context.Context, *SaveRequest) (*SaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveProxyRequest not implemented")
}
func (UnimplementedProxyRequestServiceServer) mustEmbedUnimplementedProxyRequestServiceServer() {}

// UnsafeProxyRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyRequestServiceServer will
// result in compilation errors.
type UnsafeProxyRequestServiceServer interface {
	mustEmbedUnimplementedProxyRequestServiceServer()
}

func RegisterProxyRequestServiceServer(s grpc.ServiceRegistrar, srv ProxyRequestServiceServer) {
	s.RegisterService(&ProxyRequestService_ServiceDesc, srv)
}

func _ProxyRequestService_SaveProxyRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyRequestServiceServer).SaveProxyRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/request.ProxyRequestService/SaveProxyRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyRequestServiceServer).SaveProxyRequest(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxyRequestService_ServiceDesc is the grpc.ServiceDesc for ProxyRequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyRequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "request.ProxyRequestService",
	HandlerType: (*ProxyRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveProxyRequest",
			Handler:    _ProxyRequestService_SaveProxyRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "request.proto",
}
