proxy_manager:
  host: "0.0.0.0"
  proxy_image:
    image: "go-proxy"

  shutdown_timeout: 10s

  proxy:
    - env: local
      port: 8224
      read_header_timeout: 200ms
      dial_timeout: 5s
      shutdown_timeout: 10s
      request_service_addr: ":3223"
      user_service_addr: ":3224"

    - env: dev
      port: 8225
      read_header_timeout: 500ms
      dial_timeout: 10s
      shutdown_timeout: 15s
      request_service_addr: ":3223"
      user_service_addr: ":3224"

    - env: prod
      port: 8226
      read_header_timeout: 1s
      dial_timeout: 15s
      shutdown_timeout: 20s
      request_service_addr: ":3223"
      user_service_addr: ":3224"

grpc_server:
  port: 3225
  timeout: 10s

docker_client:
  host: "unix:///var/run/docker.sock"
  timeout: 5s
  api_version: "1.44"
