proxy_manager:
  proxies:
    - env: dev
      host: 127.0.0.1
      port: 8123
      read_header_timeout: 1s
      read_timeout: 60s
      write_timeout: 60s
      shutdown_timeout: 10s

  proxy_image:
    image: "go-proxy"

  engine:
    check_timeout: 10s

  rpc_server:

docker_client:
  api_version: "1.44"
  host: "unix:///var/run/docker.sock"
  timeout: 5s
