// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: request.proto

package requestv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProxyRequestServiceClient is the client API for ProxyRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyRequestServiceClient interface {
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error)
	ProxyRequest(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	ProxyRequestByTimestamp(ctx context.Context, in *TimestampRequest, opts ...grpc.CallOption) (*TimestampResponse, error)
}

type proxyRequestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyRequestServiceClient(cc grpc.ClientConnInterface) ProxyRequestServiceClient {
	return &proxyRequestServiceClient{cc}
}

func (c *proxyRequestServiceClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, "/request.ProxyRequestService/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyRequestServiceClient) ProxyRequest(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/request.ProxyRequestService/ProxyRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyRequestServiceClient) ProxyRequestByTimestamp(ctx context.Context, in *TimestampRequest, opts ...grpc.CallOption) (*TimestampResponse, error) {
	out := new(TimestampResponse)
	err := c.cc.Invoke(ctx, "/request.ProxyRequestService/ProxyRequestByTimestamp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyRequestServiceServer is the server API for ProxyRequestService service.
// All implementations must embed UnimplementedProxyRequestServiceServer
// for forward compatibility
type ProxyRequestServiceServer interface {
	Save(context.Context, *SaveRequest) (*SaveResponse, error)
	ProxyRequest(context.Context, *GetRequest) (*GetResponse, error)
	ProxyRequestByTimestamp(context.Context, *TimestampRequest) (*TimestampResponse, error)
	mustEmbedUnimplementedProxyRequestServiceServer()
}

// UnimplementedProxyRequestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProxyRequestServiceServer struct {
}

func (UnimplementedProxyRequestServiceServer) Save(context.Context, *SaveRequest) (*SaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedProxyRequestServiceServer) ProxyRequest(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProxyRequest not implemented")
}
func (UnimplementedProxyRequestServiceServer) ProxyRequestByTimestamp(context.Context, *TimestampRequest) (*TimestampResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProxyRequestByTimestamp not implemented")
}
func (UnimplementedProxyRequestServiceServer) mustEmbedUnimplementedProxyRequestServiceServer() {}

// UnsafeProxyRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyRequestServiceServer will
// result in compilation errors.
type UnsafeProxyRequestServiceServer interface {
	mustEmbedUnimplementedProxyRequestServiceServer()
}

func RegisterProxyRequestServiceServer(s grpc.ServiceRegistrar, srv ProxyRequestServiceServer) {
	s.RegisterService(&ProxyRequestService_ServiceDesc, srv)
}

func _ProxyRequestService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyRequestServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/request.ProxyRequestService/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyRequestServiceServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyRequestService_ProxyRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyRequestServiceServer).ProxyRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/request.ProxyRequestService/ProxyRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyRequestServiceServer).ProxyRequest(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyRequestService_ProxyRequestByTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimestampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyRequestServiceServer).ProxyRequestByTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/request.ProxyRequestService/ProxyRequestByTimestamp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyRequestServiceServer).ProxyRequestByTimestamp(ctx, req.(*TimestampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxyRequestService_ServiceDesc is the grpc.ServiceDesc for ProxyRequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyRequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "request.ProxyRequestService",
	HandlerType: (*ProxyRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _ProxyRequestService_Save_Handler,
		},
		{
			MethodName: "ProxyRequest",
			Handler:    _ProxyRequestService_ProxyRequest_Handler,
		},
		{
			MethodName: "ProxyRequestByTimestamp",
			Handler:    _ProxyRequestService_ProxyRequestByTimestamp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "request.proto",
}
