# name: docker
# on: [push, pull_request]
#
# jobs:
#   docker-compose:
#     name: docker-compose
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: hoverkraft-tech/compose-action@v1.5.1
#         with:
#           compose-file: "./docker-compose.yml"
