name: lint
on: [push, pull_request]

permissions:
  contents: read

jobs:
  golangci:
    name: go-lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"

      - name: Check golangci-lint for pkg
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --config ./.golangci.yml $(find . -type f -name go.mod | sed -r 's|/[^/]+$||' | sed -e 's/$/\/.../')
