name: test
on: [push, pull_request]

jobs:
  go-test:
    name: Go test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        {
          dir:
            [
              "./pkg",
              "./services/proxy",
              "./services/proxy-manager",
              "./services/proxy-request",
              "./services/auth",
            ],
        }

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install dependencies
        working-directory: ${{ matrix.dir }}
        run: go get -v -t -d ./...

      - name: Test with cli tools
        working-directory: ${{ matrix.dir }}
        run: |
          go test -v ./...
          go test -bench=. ./...
