name: test
push: [push, pull_request]

jobs:
  go-test:
    name: Go test
    runs-on: ubuntu-latest
    staps:
      - uses: actions/checkout@v4
        with:
          go-version: "1.22"
      - name: go get & test
        run: |
          go get -v -t -d ./...
          go test -v ./...
          go test -v -bench=. ./...
